### ISSUE TITLE
Team Preview N/A 

### ISSUE THREAD

**Issue by array-carpenter** [saiemgilani/game-on-paper-app#159]
[https://gameonpaper.com/cfb/game/401635546](url)

![image](https://github.com/user-attachments/assets/c7f34f89-0540-4ca7-b424-733df88b1026)

Love this website so far and what you all are doing. Wanted to give you a heads up that it looks like the team stats for NC State, Northwestern St, UMass,  Prairie View, VMI, Morgan St, NC Central, SC State, Colgate, Gardner-Webb, Northern Iowa and Eastern Illinois  aren't appearing. I realize this is in beta so I apologize if I'm jumping the gun with this reporting. Let me know if there's anything I can do to contribute to a fix.

**Comment by akeaswaran** [comment]
Thanks for flagging this! UMass and NCState should have their stats populated in a bit. Unfortunately, we don't calculate aggregate metrics for anyone in FCS (which it looks like all of the other schools are) -- ESPN play-by-play data is generally spottier for those schools and (because of this) our models are trained on FBS vs FBS data. Sorry about that. If ESPN ever commits to providing PBP for all FCS games, we're happy to calculate metrics for those schools as well!
